### PR TITLE
Create tab to submit SEFT surveys for testing

### PR DESCRIPTION
**Pull request by insacuri**
## What? and Why?
https://trello.com/c/SayU5JBT/413-add-functionality-to-test-sdx-seft-consumer-service-using-sdx-console
There was no way before to test SEFT surveys.  This PR adds a tab to submit excel files, have them go through sdx-seft-consumer-service and end up in the FTP server.

Note: To test this, any excel file will do.  The consumer service doesn't care about the contents as long as it's a valid file.

## Checklist
  - [ ] CHANGELOG.md updated? (if required)

### CODE REVIEW

**Comment by jonnyshaw89** [comment]
Where would i get my hands on a SEFT excel file?

**Comment by jonnyshaw89** [comment]
@insacuri are the SEFT uploads not visible in the FTP tab on the console?

**Comment by insacuri** [comment]
@jonnyshaw89 I updated the comment at the top to mention that any excel file will work.
Also I hadn't thought about the FTP tab, I'll get that added

**Comment by insacuri** [comment]
I just took a look and creating a tab will be tricky as SEFT surveys go into a folder based on their survey_id.  It can work in dev as we're hard coding the survey_id, but in preprod/prod, it wouldn't work.
We'll leave the feature for now as this was a low priority bit of work anyway, and can make a card for it if it ever becomes a pain point in the future

**Review by jonnyshaw89 — APPROVED** [review]

**Review by dwyeradam — APPROVED** [review]

**Comment by jonnyshaw89** [comment]
@insacuri can you squash?

**Pull request merged**
