### PR TITLE
Added started_at data to submission

### PR DESCRIPTION
**Pull request by insacuri**
## What? and Why?
https://trello.com/c/HGU9OpOe/2173-add-dates-to-metadata-for-downstream-systems

Adding started_at data to submissions that eq is going to start ending to sdx in most submissions
## Checklist
  - [ ] CHANGELOG.md updated? (if required)

### CODE REVIEW

**Review by dcdarrell9 — DISMISSED** [review]

**Comment by benhowes** [comment]
@insacuri what should I do to test this?

**Comment by insacuri** [comment]
@benhowes have the branches with this change running in sdx-compose.  Then submit any number of the forms that changed.  They should still go through just fine (they wouldn't before without the sdx-validate change)

**Comment by benhowes** [comment]
Got it - checked out both branched and can see the started_at appearing in the output 👍

**Review by benhowes — APPROVED** [review]

**Review by MebinAbraham — APPROVED** [review]
Working as expected, validated as expected.

**Pull request merged**
