### PR TITLE
Remove decrypt tab

### PR DESCRIPTION
**Pull request by gemmai95**
Remove decrypt tab and code from service. This functionality is no longer needed.

## Checklist
  - [x] CHANGELOG.md updated? (if required)

### CODE REVIEW

**Comment by gemmai95** [comment]
[SDX Console 2.0 - Remove decrypt tab](https://trello.com/c/8h4MynpF/484-sdx-console-20-remove-decrypt-tab)

**Comment by davidmort** [comment]
does this decrypt config item still need to exist? https://github.com/ONSdigital/sdx-console/blob/remove-decrypt/console/config.py#L41

**Comment by dcdarrell9** [comment]
Decrypt gets used in submit.py as part of validate, not too sure if it's needed.
And the decrypt.html file is still there

**Review by dcdarrell9 — CHANGES_REQUESTED** [review]
Decrypt gets used in submit.py as part of validate, not too sure if it's needed.
And the decrypt.html file is still there

**Review by davidmort — CHANGES_REQUESTED** [review]
should remove this decrypt javascript code https://github.com/ONSdigital/sdx-console/blob/remove-decrypt/console/static/js/app.js#L131

**Review by davidmort — CHANGES_REQUESTED** [review]
don't think this template needs to exist anymore https://github.com/ONSdigital/sdx-console/blob/remove-decrypt/console/templates/decrypt.html

**Review by davidmort — CHANGES_REQUESTED** [review]
the decrypt tests don't need to exist anymore https://github.com/ONSdigital/sdx-console/blob/remove-decrypt/tests/test_console.py#L118

**Review by davidmort — CHANGES_REQUESTED** [review]
need to remove the decrypt info from the ui and config section from the readme

**Review by dcdarrell9 — APPROVED** [review]

**Review by davidmort — APPROVED** [review]

**Pull request merged**
