### PR TITLE
removal of clear endpoint

### PR DESCRIPTION
**Pull request by dcdarrell9**
## Checklist
  - [x] CHANGELOG.md updated? (if required)

### CODE REVIEW

**Comment by dcdarrell9** [comment]
[Empty FTP functionality in sdx-console (3)](https://trello.com/c/qlTivFpT/586-empty-ftp-functionality-in-sdx-console-3)

**Comment by insacuri** [comment]
There needs to be a PR in gitlab to remove the ENABLE_EMPTY_FTP environment variable

**Comment by insacuri** [comment]
Manifest templates need to be updated too

**Comment by dcdarrell9** [comment]
@insacuri PR added in Gitlab and removed from manifest

**Review by insacuri — APPROVED** [review]

**Pull request merged**
