### PR TITLE
Refactor user authentication and creation to work with compose

### PR DESCRIPTION
**Pull request by gemmai95**
Fix login issues when being used with compose and add missing requirements.

## Checklist
  - [x] CHANGELOG.md updated? (if required)

**Does not include decrypt functionality**

### CODE REVIEW

**Comment by gemmai95** [comment]
[Fix issues in sdx-console (5)](https://trello.com/c/zc9j7t3F/451-fix-issues-in-sdx-console-5)

**Review by dcdarrell9 — COMMENTED** [review]
Should we need to running postgres locally for the tests to work?

**Comment by gemmai95** [comment]
@dcdarrell9 This has been raised in another card

**Comment by warrenbailey** [comment]
I don't think the title and description of this PR reflect the work that's actually been done. It's looks like a big structural change. Can we update it?

**Comment by warrenbailey** [comment]
Also why is the PR requesting a merge into the merge-new-console branch and not 2.0?

**Comment by gemmai95** [comment]
@warrenbailey The reason it's merging into the new branch is that the new branch has all the changes from 2.0 and can merge cleanly to master. 2.0 has a lot of merge conflicts. We can change this if necessary.

**Pull request merged**
